### ISSUE TITLE
USER STORY: Search results and the number of results

### ISSUE THREAD

**Issue by HerFri** [HerFri/RetroResell#14]
EPIC: Product Categorization & Browsing

As a **User/Shopper** I can **see what I've searched for and the number of results** so that **I can quickly see whether the product I want is available.**

**Acceptance Criteria**
- After doing a search query, Users/Shoppers should see a field in the products page that shows how many search results have been found
- If a explicit category has been searched for, e.g. consoles, this should be displayed as a badge under the product's page heading

**Tasks**
- [x] Add span and {{ products|length }} condition to display the current number of found products for the search query in products.html
- [x] Add badge in products.html that displays the category that has been searched for
- [x] Add request.GET condition for queries and context to 'all_products' function in views.py
