### ISSUE TITLE
USER STORY: Select quantity of a product when purchasing it

### ISSUE THREAD

**Issue by HerFri** [HerFri/RetroResell#15]
EPIC: Ordering and Checkout 

As a **Shopper** I can **easily select the quantity of a product when purchasing it** so that **I can ensure that I don't accidentally select the wrong quantity.**

**Acceptance Criteria**
- With the help of buttons, shoppers can adjust the quantity of their desired products on the product detail page.

**Tasks**

- [x] Create 'quantity_input_script.html' that comprises JavaScript scripts for handling changing quantity of products
- [x] Include 'quantity_input_script.html' to 'product_detail.hmtl'
- [x] Style the buttons
