### ISSUE TITLE
USER STORY: View items in cart/bag to be purchased

### ISSUE THREAD

**Issue by HerFri** [HerFri/RetroResell#16]
EPIC: Ordering and Checkout

As a **Shopper** I can **view items in my cart/bag to be purchased** so that **I can identify the total cost of my purchase and all items I will receive.**

**Acceptance Criteria**
- By clicking the cart icon in the upper right corner, users are directed to the bag page.

**Tasks**

- [x] Create bag app
- [x] Create view_bag view in views.py in the bag app
- [x] Create bag template and add customized styling
