### ISSUE TITLE
USER STORY: Adjust quantity of individual items in cart

### ISSUE THREAD

**Issue by HerFri** [HerFri/RetroResell#17]
EPIC: Ordering and Checkout 

As a **Shopper** I can **easily select the quantity of a product when purchasing it** so that **I can easily make changes to my purchase before checkout.**

**Acceptance Criteria**
- With the help of buttons, shoppers can adjust the quantity of their desired products in the cart before checkout.

**Tasks**

- [x] Create 'adjust_bag' function in views.py
- [x] Create 'remove_from_bag' function in views.py
- [x] Create JavaScript scripts for handling changing quantity, updating and deleting of products on clicking the buttons in bag.html
