### ISSUE TITLE
USER STORY: Enter personal details and payment information

### ISSUE THREAD

**Issue by HerFri** [HerFri/RetroResell#18]
EPIC: Ordering and Checkout 

As a **Shopper** I can **easily enter my personal details and payment information** so that **I can check out quickly and with no hassles.**

**Acceptance Criteria**
Customers should be able to view an order form after placing an order, where they are asked to enter their personal details like full name and delivery address and their credit card details to place the order.

**Tasks**

- [x] Create file 'checkout.html' and input fields for personal and payment details in the order form
- [x] Add CSS for the order form
- [x] Implement Stripe for secure payment
- [x] Use Stripe webhooks and add Stripe Javascript to the 'checkout.html' file
