### ISSUE TITLE
USER STORY: Receive an email confirmation after checking out

### ISSUE THREAD

**Issue by HerFri** [HerFri/RetroResell#21]
EPIC: Ordering & Checkout

As a **Shopper** I can **receive an email confirmation after checking out** so that **I can keep the confirmation of what I've purchased for my records.**

**Acceptance Criteria**
Via the Webhook handler, customers will receive a confirmation email of their order after checking out to the email address that has been provided in the order form.

**Tasks**
- [x] Create confirmation_email_body.txt & confirmation_email_subject.txt
- [x] Customize Email text 
- [x] Add '_send_confirmation_email' method to webhook_handler.py
