### ISSUE TITLE
USER STORY: CRUD: Create, edit, delete a product

### ISSUE THREAD

**Issue by HerFri** [HerFri/RetroResell#22]
EPIC: Product Management

As a **Store Owner/Admin** I can **add (create), edit and delete products** so that **I can update the product selection of my store.**

**Acceptance Criteria**
The Store Owner/Admin should have an admin panel that helps him in the management of the products of the store.

**Tasks**

- [x] Set up admin panel
- [x] Add Category Model
- [x] Add Product model
