### ISSUE TITLE
USER STORY: CRUD functionality for products in the front end

### ISSUE THREAD

**Issue by HerFri** [HerFri/RetroResell#23]
EPIC: Product Management

As a **Store Owner/Admin** I can **add (create), edit and delete a product from the front end of the site** so that **I can change product prices, descriptions, images, and other product criteria without the need of doing this in the admin panel.**

**Acceptance Criteria**
The Store Owner/Admin can click on the 'Product Management' dropdown option of 'My Account' in the navbar to be lead to the 'Add a Product' form, where they can fill in the details of a new product and eventually add it to the product selection. Moreover, the Store Owner/Admin can edit and delete newly added and already existing products.

**Tasks**

- [x] Add class ProductForm
- [x] Add views, URLs and templates
- [x] Add code for functionality in views.py
- [x] Add add_product.html & edit_product.html
- [x] Add Edit / Delete URLs to products.html & product_detail.html
- [x] Add message (toast) for successfully adding, editing and deleting a product, 
- [x] Add Javascript block for displaying text when uploading an image file for a product
