### ISSUE TITLE
USER STORY: Site User Navigation

### ISSUE THREAD

**Issue by HerFri** [HerFri/RetroResell#25]
EPIC: Navigation

As a **Site User** I can **easily navigate on the site** so that **I can find the products available.**

**Acceptance Criteria**
- The user should be able to intuitively navigate from page to page by using the navigation bar and menu icons.
- The navbar menu should be responsive on all devices.

**Tasks**
- [x] Create a user-friendly navigation menu that leads to the corresponding pages.
- [x] Create a responsive navbar on various devices.
- [x] Add menu icons for 'My Account', 'Wishlist' and 'Shopping Cart'
