### ISSUE TITLE
USER STORY: Show Messages (Toasts)

### ISSUE THREAD

**Issue by HerFri** [HerFri/RetroResell#27]
EPIC:  User Feedback

As a **User/Shopper** I can **see success messages after adding products to the cart and complete a purchase and info messages when posting/deleting an inquiry and posting/deleting a comment** so that **I will be informed immediately about my actions.**

**Acceptance Criteria**

Users/Shoppers should see a message (toast) pop up in the right corner of the website when they successfully execute any of the above mentioned operations.

**Tasks**

- [x] Add toast templates
- [x] From django.contrib import messages
- [x] Add messages.success/error/info for different functions in views.py and the respective message
