### ISSUE TITLE
USER STORY: Add products to wishlist

### ISSUE THREAD

**Issue by HerFri** [HerFri/RetroResell#28]
EPIC: User Interactivity

As an **authenticated User** I can **add products to my wishlist** so that **I will not forget about products that I might want to buy in the future**.

**Acceptance Criteria**
Authenticated Users can add up to five products to their wishlist.

**Tasks**
- [x] Create app wishlist
- [x] Add Wishlist view and add/delete wishlist item functions  to views.py
- [x] Add 'Add to Wishlist' button to product_detail.html
- [x] Add wishlist icon next to 'My Account' in base.html
