### ISSUE TITLE
USER STORY: CRUD: Comment on Products

### ISSUE THREAD

**Issue by HerFri** [HerFri/RetroResell#29]
EPIC: User Interactivity

As an **authenticated User** I can **create, read, update and delete comments about products** so that **I can share my opinion about certain products and comment on other user's comments.**

**Acceptance Criteria**
Authenticated Users can write comments in the Product Detail Page and update/delete those aswell. When writting a comment, the user is informed by a message at the location of the comment form that the comment is waiting approval by the admin. When the comment has been approved by the admin in the admin panel, the comment will be viewed.

**Tasks**
- [x] add Comment model in models.py of the products app
- [x] add request.method == 'POST' condition to product_detail function in views.py
- [x] add CommentForm to forms.py
- [x] add edit_comment & delete comment functions to views.py
- [x] add comment section and template language conditions to product_detail.html
- [x] add  message 'Your comment is awaiting approval' in the location of the comment form
- [x] add message (toast) when successfully editing/deleting a comment
