### ISSUE TITLE
USER STORY: Post Inquiries

### ISSUE THREAD

**Issue by HerFri** [HerFri/RetroResell#30]
EPIC: User Interactivity

As an **authenticated User/Shopper** I can **post an inquiry** so that **I can let the website administrator know that something is wrong with my order or missing, propose a sell offer or to state any other issue connected to the website**.

**Acceptance Criteria**
Authenticated Users are able to see the 'My Inquiries' dropdown item after clicking on the 'My Account' Icon. On the 'My Inquiries' page, users can fill a form for an inquiry and submit it. After submitting, they can find their inquiry in the 'Inquiry History' section and view the details after clicking the 'See Details' button. On the Inquiry details page, users can delete their inquiry by clicking the 'Delete Inquiry' button, which will lead them to the inquiry delete confirmation page, where they have to confirm, that they want to delete their inquiry.

**Tasks**
- [x] Create inquiries app
- [x] Add 'user_inquiry', 'view_inquiry' and 'delete_inquiry' functions in views.py
- [x] Add 'My Inquiries' dropdown item for 'My Account' icon
- [x] Add templates, buttons and template language
