### ISSUE TITLE
USER STORY: View comments about Products

### ISSUE THREAD

**Issue by HerFri** [HerFri/RetroResell#34]
EPIC: User Interactivity

As a **User** I can **read comments about the products of the website** so that **I can get an idea about the experiences and opinions of different users about certain products of the website**.

**Acceptance Criteria**
Users can view the comment section of the Product Detail Page.

**Tasks**
- [x] add Comment model in models.py of the products app
- [x] add request.method == 'POST' condition to product_detail function in views.py
- [x] add CommentForm to forms.py
- [x] add comment section and Django template language conditions to product_detail.html
