### ISSUE TITLE
USER STORY: View product by categories

### ISSUE THREAD

**Issue by HerFri** [HerFri/RetroResell#35]
EPIC: Product Categorization and Browsing

As a **User/Shopper** I can **view products by specific product categories** so that **I can easily find the product I am looking for**.

**Acceptance Criteria**
Website User should see clearly labeled links or options on the website's interface which allows them to find products categorized or ordered by specific categories, like Category, Platform or Rating. Clicking on a category should direct the user to a page that displays only products belonging to that category.

**Tasks**
- [x]  Create “Category” model and create the categories in the admin panel.
- [x] Add product categories as dropdown items of the navbar on the home page
- [x] Add a request.GET condition and other conditions for 'sort, 'category', 'platform' and 'q' to the 'all_products' function in views.py of the products app that filters the products by the different categories .
- [x] Add URLs and query strings to dropdown items of the navbar
