### ISSUE TITLE
USER STORY: Register for an account

### ISSUE THREAD

**Issue by HerFri** [HerFri/RetroResell#5]
EPIC: User Registration, Login and Profile

As a **Site User** I can **easily register for an account** so that **I can have a personal account which allows me additional features like viewing my order history, adding products to my wishlist and writing comments about products**.

**Acceptance Criteria**

- Users should be able to see the "My Account" icon the the top right corner that opens up a dropdown menu by clicking on it
- In the dropdown menu, unautherized users should see the "Register" option, that should lead them to the Register page after clicking on it.
- After successfully registering, users should be prompted with a message on the page that they have registered successfully

**Tasks**

- [x] Add Register option to Account icon dropdown menu 
- [x] Set up Allauth library for handling the user's authentication and registration and handling the sending of the confirmation email 
- [x] Add success message that informs users that a confirmation email has been sent
