### ISSUE TITLE
USER STORY: Receive email confirmation after registering

### ISSUE THREAD

**Issue by HerFri** [HerFri/RetroResell#8]
EPIC: User Registration, Login and Profile

As a **Site User** I will **receive an email confirmation after registering** so that **I can verify that my account registration was successful**.

**Acceptance Criteria**
After registering for an account, users will receive an email confirmation with a provided link that has to be clicked on to successfully confirm the account registration.

**Tasks**
- [x] Add Allauth library
- [x] Customize verification_sent.html template
- [x] Add message (toast) that informs the user that a confirmation email has been sent to the user with the request to confirm it.
