### ISSUE TITLE
USER STORY: Personalized User Profile and Order History

### ISSUE THREAD

**Issue by HerFri** [HerFri/RetroResell#9]
EPIC: User Registration, Login and Profile

As an **Authenticated User/Shopper** I can **have a personalized user profile** so that **I can view my personal order history and order confirmations and save/update my payment/delivery information**.

**Acceptance Criteria**
- After logging in, authenticated users can click on the 'My Profile' dropdown item of the 'My Account' icon and view their order history.
- By having a personalized User Profile, users can save their delivery information and have a record of their order history.

**Tasks**
- [x] Create Profiles app
- [x] Add profile.html template
- [x] Add 'profile' and 'order_history' functions to views.py
- [x] Add Django template language to profile.html to view all previous orders and update payment/delivery information
